<template>
  <div v-if="show" class="modal-overlay" @click.self="close">
    <div class="modal-body">
      <div class="modal-header">
        <div>
          <p class="modal-label">策略运行结果</p>
          <h3>运行 ID: {{ runId }}</h3>
        </div>
        <button class="close-btn" @click="close">✕</button>
      </div>

      <div class="modal-content">
        <div v-if="assets.length" class="results-table-container">
          <table class="results-table">
            <thead>
              <tr>
                <th>标的</th>
                <th>建议操作</th>
                <th>建议方向</th>
                <th>信号强度</th>
                <th>建议权重</th>
                <th>维度分析</th>
                <th>风险标记</th>
                <th>备注</th>
              </tr>
            </thead>
            <tbody>
              <tr v-for="asset in assets" :key="asset.symbol">
                <td><span class="symbol-tag">{{ asset.symbol }}</span></td>
                <td>
                  <span :class="['action-tag', (asset.action || '').toLowerCase()]">
                    {{ translateAction(asset.action) }}
                  </span>
                </td>
                <td>
                  <span :class="['direction-tag', (asset.direction || '').toLowerCase()]">
                    {{ translateDirection(asset.direction) }}
                  </span>
                </td>
                <td>
                  <div class="strength-bar-wrap">
                    <div class="strength-bar" :style="{ width: (asset.signal_strength ?? 0) + '%' }"></div>
                    <span class="strength-value">{{ asset.signal_strength?.toFixed(2) ?? '--' }}</span>
                  </div>
                </td>
                <td>{{ ((asset.weight ?? 0) * 100).toFixed(2) }}%</td>
                <td>
                  <div class="dimensions">
                    <span v-for="(val, key) in asset.signal_dimensions" :key="key" class="dim-tag">
                      {{ translateDimension(key) }}: {{ typeof val === 'number' ? val.toFixed(2) : val }}
                    </span>
                  </div>
                </td>
                <td>
                  <div class="risk-flags">
                    <span v-for="flag in asset.risk_flags" :key="flag" class="risk-tag">
                      {{ translateRiskFlag(flag) }}
                    </span>
                    <span v-if="!asset.risk_flags?.length" class="safe-tag">正常</span>
                  </div>
                </td>
                <td class="notes">{{ translateNotes(asset.notes) }}</td>
              </tr>
            </tbody>
          </table>
        </div>
        <div v-else class="empty-state">
            <p>该策略未发现符合条件的标的或正在扫描中...</p>
        </div>
      </div>

      <div class="modal-actions">
        <button class="primary-btn" @click="close">关闭</button>
      </div>
    </div>
  </div>
</template>

<script setup lang="ts">
import type { StrategyRunAssetView } from '../api/client';

defineProps<{
  show: boolean;
  runId: string;
  assets: StrategyRunAssetView[];
}>();

const emit = defineEmits<{
  (e: 'close'): void;
}>();

function translateDimension(key: string): string {
  const map: Record<string, string> = {
    'volume': '成交量分析',
    'momentum': '价格动量',
    'sentiment': '市场情绪',
    'volatility': '波动率',
    'growth': '增长潜力'
  };
  return map[key.toLowerCase()] || key;
}

function translateRiskFlag(flag: string): string {
  const map: Record<string, string> = {
    'volatile': '波动巨大',
    'high_risk': '高风险',
    'suspicious': '异常波动',
    'normal': '正常'
  };
  return map[flag.toLowerCase()] || flag;
}

function translateAction(action: string | null | undefined): string {
  if (!action) return '--';
  const map: Record<string, string> = {
    'buy': '买入',
    'sell': '卖出',
    'hold': '持有',
    'increase': '加仓',
    'decrease': '减仓'
  };
  return map[action.toLowerCase()] || action;
}

function translateDirection(direction: string | null | undefined): string {
  if (!direction) return '--';
  const map: Record<string, string> = {
    'long': '做多',
    'short': '做空',
    'neutral': '中性'
  };
  return map[direction.toLowerCase()] || direction;
}

function translateNotes(note: string | null | undefined): string {
  if (!note) return '--';
  if (note.toLowerCase().includes('generated by strategy engine')) {
    return '策略引擎自动生成';
  }
  return note;
}

function close() {
  emit('close');
}
</script>

<style scoped>
.modal-overlay {
  position: fixed;
  inset: 0;
  background: rgba(15, 23, 42, 0.85);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 1000;
  backdrop-filter: blur(4px);
}

.modal-body {
  background: #1e293b;
  width: 90%;
  max-width: 1000px;
  max-height: 85vh;
  border-radius: 16px;
  border: 1px solid rgba(56, 189, 248, 0.2);
  display: flex;
  flex-direction: column;
  box-shadow: 0 25px 50px -12px rgba(0, 0, 0, 0.5);
}

.modal-header {
  padding: 20px 24px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
  display: flex;
  justify-content: space-between;
  align-items: center;
}

.modal-label {
  font-size: 0.75rem;
  color: #38bdf8;
  text-transform: uppercase;
  letter-spacing: 0.05em;
  margin: 0 0 4px 0;
}

h3 {
  margin: 0;
  font-size: 1.25rem;
  color: #f1f5f9;
}

.close-btn {
  background: transparent;
  border: none;
  color: #94a3b8;
  font-size: 1.25rem;
  cursor: pointer;
  padding: 4px;
}

.modal-content {
  padding: 24px;
  overflow-y: auto;
  flex: 1;
}

.results-table-container {
  border-radius: 8px;
  overflow: hidden;
  border: 1px solid rgba(255, 255, 255, 0.05);
}

.results-table {
  width: 100%;
  border-collapse: collapse;
  text-align: left;
}

.results-table th {
  background: rgba(30, 41, 59, 0.5);
  padding: 12px 16px;
  font-size: 0.85rem;
  color: #94a3b8;
  font-weight: 600;
  border-bottom: 1px solid rgba(255, 255, 255, 0.1);
}

.results-table td {
  padding: 16px;
  border-bottom: 1px solid rgba(255, 255, 255, 0.05);
  font-size: 0.9rem;
  color: #e2e8f0;
}

.symbol-tag {
  background: rgba(56, 189, 248, 0.1);
  color: #38bdf8;
  padding: 4px 8px;
  border-radius: 4px;
  font-weight: 600;
  font-family: monospace;
}

.action-tag {
  padding: 3px 8px;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 600;
}
.action-tag.buy { background: rgba(34, 197, 94, 0.15); color: #4ade80; }
.action-tag.sell { background: rgba(239, 68, 68, 0.15); color: #f87171; }
.action-tag.hold { background: rgba(148, 163, 184, 0.15); color: #cbd5e1; }
.action-tag.increase { background: rgba(16, 185, 129, 0.2); color: #34d399; }

.direction-tag {
  padding: 3px 8px;
  border-radius: 4px;
  font-size: 0.75rem;
  font-weight: 600;
  border: 1px solid rgba(255, 255, 255, 0.1);
}
.direction-tag.long { border-color: #4ade80; color: #4ade80; }
.direction-tag.short { border-color: #f87171; color: #f87171; }

.strength-bar-wrap {
  width: 120px;
  height: 20px;
  background: rgba(255, 255, 255, 0.05);
  border-radius: 10px;
  position: relative;
  overflow: hidden;
}

.strength-bar {
  height: 100%;
  background: linear-gradient(90deg, #38bdf8, #818cf8);
}

.strength-value {
  position: absolute;
  top: 50%;
  left: 50%;
  transform: translate(-50%, -50%);
  font-size: 0.7rem;
  font-weight: 700;
  color: white;
  text-shadow: 0 1px 2px rgba(0,0,0,0.5);
}

.dimensions {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.dim-tag {
  font-size: 0.7rem;
  background: rgba(255, 255, 255, 0.05);
  padding: 2px 6px;
  border-radius: 3px;
  color: #cbd5e1;
}

.risk-flags {
  display: flex;
  flex-wrap: wrap;
  gap: 4px;
}

.risk-tag {
  background: rgba(239, 68, 68, 0.1);
  color: #f87171;
  font-size: 0.7rem;
  padding: 2px 6px;
  border-radius: 3px;
  border: 1px solid rgba(239, 68, 68, 0.2);
}

.safe-tag {
    color: #4ade80;
    font-size: 0.7rem;
}

.notes {
    font-size: 0.8rem;
    color: #94a3b8;
    max-width: 200px;
}

.empty-state {
    text-align: center;
    padding: 40px;
    color: #94a3b8;
}

.modal-actions {
  padding: 20px 24px;
  border-top: 1px solid rgba(255, 255, 255, 0.1);
  display: flex;
  justify-content: flex-end;
}

.primary-btn {
  background: #38bdf8;
  color: #0f172a;
  border: none;
  padding: 10px 24px;
  border-radius: 8px;
  font-weight: 600;
  cursor: pointer;
  transition: all 0.2s;
}

.primary-btn:hover {
  background: #0ea5e9;
  transform: translateY(-1px);
}
</style>
